server:  port: 9003
eureka:  client:    serviceUrl:      defaultZone: http://localhost:8767/eureka          
spring:
  application:    name: api-gateway
  cloud:
    gateway:
      routes:       - id: basic-service         uri: http://localhost:9001/basic-service         predicates:         - Path=/basic/**              
          