server:  port: 9003
eureka:  client:    serviceUrl:      defaultZone: http://192.168.1.21:8767/eureka       
spring:
  application:    name: api-gateway
  cloud:
    gateway:
      routes:       - id: basic-service           uri: lb://basic-service         predicates:         - Path=/basic/**                     
          